version: '3.8'

services:
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ServiceUrls__VideoStreaming=http://video-streaming:8080
      - ServiceUrls__VideoMetadata=http://video-metadata:8080
      - ServiceUrls__VideoViews=http://video-views:8080
      - ServiceUrls__VideoUpload=http://video-upload-queue:8080
      - ServiceUrls__CommentService=http://comment-service:8080
      - ServiceUrls__IdentityService=http://identity-service:8080
    depends_on:
      - video-streaming
      - video-metadata
      - video-views
      - video-upload-queue
      - comment-service
      - identity-service
    restart: unless-stopped

  admin-gateway:
    build:
      context: ./services/AdminGateway
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ServiceUrls__VideoStreaming=http://video-streaming:8080
      - ServiceUrls__VideoMetadata=http://video-metadata:8080
      - ServiceUrls__VideoViews=http://video-views:8080
      - ServiceUrls__VideoUpload=http://video-upload-queue:8080
      - ServiceUrls__CommentService=http://comment-service:8080
      - ServiceUrls__VideoStorage=http://video-storage:8080
      - ServiceUrls__IdentityService=http://identity-service:8080
    depends_on:
      - video-streaming
      - video-metadata
      - video-views
      - video-upload-queue
      - comment-service
      - video-storage
      - identity-service
    restart: unless-stopped

  video-storage:
    build:
      context: ./services/FileSystemVideoStorage
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    volumes:
      - video_data:/app/videos
    restart: unless-stopped

  video-upload-queue:
    build:
      context: ./services/VideoUploadQueue
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      rabbitmq:
        condition: service_healthy
      video-storage:
        condition: service_started
    restart: unless-stopped

  video-streaming:
    build:
      context: ./services/VideoStreaming
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__MongoDb=${MONGO_STREAMING_CONNECTION_STRING}
    depends_on:
      video-streaming-db:
        condition: service_started
      video-storage:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  video-views:
    build:
      context: ./services/VideoViews
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__MongoDb=${MONGO_VIEWS_CONNECTION_STRING}
      - ConnectionStrings__RabbitMq=${RABBITMQ_CONNECTION_STRING}
    depends_on:
      video-views-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  video-metadata:
    build:
      context: ./services/VideoMetadata
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__MongoDb=${MONGO_METADATA_CONNECTION_STRING}
      - ConnectionStrings__RabbitMq=${RABBITMQ_CONNECTION_STRING}
    depends_on:
      video-metadata-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  comment-service:
    build:
      context: ./services/CommentService
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${COMMENT_DB_CONNECTION_STRING}
    depends_on:
      comment-db:
        condition: service_started
    restart: unless-stopped

  identity-service:
    build:
      context: ./services/IdentitiyService
      dockerfile: Dockerfile
    ports:
      - "8086:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${IDENTITY_DB_CONNECTION_STRING}
      - Jwt__Secret=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
    depends_on:
      identity-db:
        condition: service_started
    restart: unless-stopped

  # ----------Database----------
  video-streaming-db:
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - video_streaming_data:/data/db

  video-views-db:
    restart: always
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - video_views_data:/data/db

  video-metadata-db:
    restart: always
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - video_metadata_data:/data/db

  comment-db:
    restart: always
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${COMMENT_DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - comment_data:/var/lib/mysql

  identity-db:
    restart: always
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${IDENTITY_DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - identity_data:/var/lib/mysql

  # ----------MessageQueue----------
  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 30s
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  video_data:
  video_streaming_data:
  video_views_data:
  video_metadata_data:
  comment_data:
  identity_data:
  rabbitmq_data:
